@startuml Warrior
namespace UEAPI{

    class APawn{
        + void PossessedBy()
    }

    class ACharacter extends APawn {}

    class UAnimInstance{
        + NativeInitializeAnimation()
        + NativeThreadSafeUpdateAnimation()
    }

    package GAS {

        interface IAbilitySystemInterface {
            + UAbilitySystemComponent* GetAbilitySystemComponent()
        }

        class UGameplayAbility{
            # void OnGiveAbility()
            # void EndAbility()
        }

        class UAbilitySystemComponent{}

        class UAttributeSet{}

        class UDataAsset{}

    }/'package GAS'/

}/'namespace UEAPI'/


namespace Warrior{ 

    package AbilitySystem{

        enum EWarriorAbilityActivationPolicy {
            OnTriggered,
            OnGiven,
        }

        class UWarriorGameplayAbility{
            # EWarriorAbilityActivationPolicy AbilityActivationPolicy
        }

        class UWarriorAbilitySystemComponent{}

        class UWarriorAttributeSet{}

    }/'package AbilitySystem'/

    package Character{

        class AWarriorBaseCharacter {
            + UWarriorAbilitySystemComponent* GetWarriorAbilitySystemComponent()
            + UWarriorAttributeSet* GetWarriorAttributeSet()
            __
            # UWarriorAbilitySystemComponent* WarriorAbilitySystemComponent
            # UWarriorAttributeSet* WarriorAttributeSet
        }

        class AWarriorHeroCharacter extends AWarriorBaseCharacter{ 
            # void BeginPlay() override
            # void SetupPlayerInputComponent() override
            __
            - USpringArmComponent* CameraBoom
            - UCameraComponent* FollowCamera
            - UDataAsset_InputConfig* InputConfigDataAsset
            __
            - void Input_Move()
            - void Input_Look()
        }

    }/'package Character'/

    package AnimInstance{

        class UWarriorBaseAnimInstance{}

        class UWarriorCharacterAnimInstance extends UWarriorBaseAnimInstance{
            # AWarriorBaseCharacter* OwningCharacter
            # UCharacterMovementComponent* OwningMovementComponent
            # float GroundSpeed
            # bool bHasAcceleration
        }

        class UWarriorHeroAnimInstance extends UWarriorCharacterAnimInstance{
            # AWarriorHeroCharacter* OwningHeroCharacter
            # bool bShouldEnterRelaxState
            # float EnterRelaxStateThreshold
            # float IdleElapsedTime
        }

        class UWarriorHeroLinkedAnimLayer extends UWarriorBaseAnimInstance{}
    }/'package AnimInstance'/

    package DataAssets{

        class UDataAsset_StartUpBase extends UEAPI.GAS.UDataAsset{ 
            + void GiveToAbilitySystemComponent()
            __
            # TArray<TSubclassOf<UWarriorGameplayAbility>> ActivateOnGivenAbilities
            # TArray<TSubclassOf<UWarriorGameplayAbility>> ReactiveAbilities;
            __
            # void GrantAbilities()
        }

        class UDataAsset_HeroStartUpData extends UDataAsset_StartUpBase{}

    }/'package DataAssets'/

}/'namespace Warrior'/

Warrior.AbilitySystem.UWarriorGameplayAbility -up-|> UEAPI.GAS.UGameplayAbility
Warrior.AbilitySystem.UWarriorGameplayAbility::AbilityActivationPolicy -[bold]-* Warrior.AbilitySystem.EWarriorAbilityActivationPolicy
Warrior.AbilitySystem.UWarriorAbilitySystemComponent -up-|> UEAPI.GAS.UAbilitySystemComponent
Warrior.AbilitySystem.UWarriorAttributeSet -up-|> UEAPI.GAS.UAttributeSet

Warrior.Character.AWarriorBaseCharacter -up-|>  UEAPI.ACharacter
Warrior.Character.AWarriorBaseCharacter .up.|>  UEAPI.GAS.IAbilitySystemInterface

Warrior.AnimInstance.UWarriorBaseAnimInstance -up-|> UEAPI.UAnimInstance

@enduml